
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      # - name: Enable Cache
      #   id: cache-action
      #   uses: actions/cache@v2 
      #   with:
      #     path: cache-folder
      #     key: ${{ runner.os }}-${{ hashFiles('cache-folder/cache-me') }}
    
      - name: Hello world action step
        id: hello
        uses: musset0/my-action@main
        with:
          who-to-greet: 'mussett'
          
      # - name: dreamli docker action
      #   id: my
      #   uses: dreamli0/my-action@main
      #   with: 
      #     who-to-greet: 'dreamli' 
      
      # - name: Hello world action step
      #   id: hello
      #   uses: musset0/dock_container_action@v1
      #   with:
      #     who-to-greet: 'mussett'
          
      # - name: dreamli docker action
      #   id: my
      #   uses: dreamli0/docker_container_action@main
      #   with: 
      #     who-to-greet: 'dreamli' 
    
      - name: Get the output time
        run: ${{steps.hello.outputs.time }}

      # - name: Verify we have our cached file 
      #   run: |
      #     echo `pwd` 
      #     cat cache-folder/cache-me



  
