
on: [push]

jobs:
  use:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Enable Cache
      id: cache-action
      uses: actions/cache@v2
      with:
        path: cache-folder  
        key: ${{ runner.os }}-${{ hashFiles('cache-folder/cache_me') }}

    # - name: Use or generate the cache
    #   if: ${{ steps.cache-action.outputs.cache-hit != 'true' }}
    #   run: |
    #     mkdir cache-folder
    #     echo 3 > cache-folder/cache_me 

    - name: my action step
      id: my
      uses: musset0/my-action@v1.1.2
      with: 
        who-to-greet: 'musset_main__' 
        
    - shell: bash
      if: ${{ steps.cache-action.outputs.cache-hit == 'true' }}
      run: |
          cat cache-folder/cache_me
          
    - name: Verify we have our cached file 
      run: |
        echo `pwd` 
        cat cache-folder/cache_me

  
