on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    outputs:
      output1: ${{ steps.hello.outputs.time }}
    steps:
      
      - name: dreamli action step
        id: hello
        uses: dreamli0/my-action@main
        with:
          hi-there: ${{ secrets.AWS_SECRETS }}
          
      - name: my action step
        id: my
        uses: musset0/my-action@v1.1.2
        with:
          who-to-greet: 'mussetttt'
         
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The Greeting time was ${{ steps.hello.outputs.time }}"
  
  job2:
    runs-on: ubuntu-latest
    needs: hello_world_job
    steps:
      - env:
          OUTPUT1: ${{needs.hello_world_job.outputs.output1}}
        run: echo "$OUTPUT1"
      
