name: Share data between jobs

on: [push]

jobs:
  
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          expr 3 + 7 > artifact/math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: artifact/math-homework.txt
          
      - name: my action step
        id: my
        uses: musset0/my-action@v1.1.2
        with:
          who-to-greet: 'musset'

  
