on: [push]

jobs:
  call-workflow-passing-data:
    uses: dreamli0/test_actions_02/.github/workflows/resuable_workflow_job_public.yml@main
    with:
      who-to-greet: "musset"
      hi-there: "dreamli"
  
  job2:
    runs-on: ubuntu-latest
    needs: call-workflow-passing-data
    steps:
      - env:
          OUTPUT1: ${{needs.call-workflow-passing-data.outputs.output1}}
        run: echo ${{needs.call-workflow-passing-data.outputs.output1}}
      
