on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: my action step
        id: my
        uses: dreamli0/my-action@v1.1.2
        with:
          who-to-greet: 'musset'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The Greeting time was ${{ steps.hello.outputs.time }}"
