on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - name: dreamli action step
        uses: dreamli0/my-action@main
        with:
          hi-there: ${{ secrets.AWS_SECRETS }}
        
      - name: my action step
        id: my
        uses: musset0/my-action@v1.1.2
        with:
          who-to-greet: 'musset'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The Greeting time was ${{ steps.hello.outputs.time }}"
