name: Caching Test

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:

    - name: Enable Cache
      id: cache-action
      uses: actions/cache@v2
      with:
        path: cache-folder
        key: ${{ runner.os }}-${{ hashFiles('cache-folder/hello') }}

    - name: Use or generate the cache
      if: steps.cache-action.outputs.cache-hit != 'true'
      run: mkdir cache-folder && echo 2 > cache-folder/hello

    - name: Verify we have our cached file
      run: |
        echo `pwd` 
        cat cache-folder/hello

  use:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Enable Cache
      id: cache-action
      uses: actions/cache@v2
      with:
        path: cache-folder
        key: ${{ runner.os }}-${{ hashFiles('cache-folder/hello') }}
        
    - shell: bash
      if: steps.cache-action.outputs.cache-hit == 'true'
      run: |
          value=`cat cache-folder/hello`
          echo $value \* 8 
    

      
