name: Share data between jobs

on: [push]

jobs:
  
  job_1:
    name: Add 3 and 7
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          expr 3 + 7 > artifact/math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: artifact/math-homework.txt
          
      - name: my action step
        id: my
        uses: musset0/my-action@v1.1.2
        with:
          who-to-greet: 'mussettt'

  # job_2:
  #   name: Multiply by 8
  #   needs: job_1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download math result for job 1
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: homework
          
  #     - name: Display structure of downloaded files
  #       run: ls -R
        
  #     - shell: bash
  #       run: |
  #         value=`cat math-homework.txt`
  #         expr $value \* 8 > math-homework.txt
  #     - name: Upload math result for job 2
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: homework
  #         path: math-homework.txt

  # job_3:
  #   name: Display results
  #   needs: job_2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download math result for job 2
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: homework
          
  #     - name: Display structure of downloaded files
  #       run: ls -R
        
  #     - name: Print the final result
  #       shell: bash
  #       run: |
  #         value=`cat math-homework.txt`
  #         echo The result is $value
